services:
  - type: web
    name: solmates-signaling
    env: node
    region: frankfurt
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true